-- insert into hotel(id, name, address, zip) values (1, 'Test Hotel 1', 'Test Street 1', '000001');
-- insert into hotel(id, name, address, zip) values (2, 'Test Hotel 2', 'Test Street 2', '000002');
-- insert into hotel(id, name, address, zip) values (3, 'Test Hotel 3', 'Test Street 3', '000003');
-- insert into hotel(id, name, address, zip) values (4, 'Test Hotel 4', 'Test Street 4', '000004');
